### ISSUE TITLE
Some issues about angle of view

### ISSUE THREAD

**Issue by Metal-joker** [WeiTang114/BlenderPhong#1]
I use your project to prepare `mvcnn` like dataset, but compare with the original dataset, your project only has four angles and not spin smooth.

How can I prepare dataset like `modelnet40v1` that each model has 12 views and 12 views spin smooth?

Thanks for all the help.

**Comment by WeiTang114** [comment]
Hi, please modify `cameras` in [phong.py](https://github.com/WeiTang114/BlenderPhong/blob/master/phong.py#L21) for whatever directions you like. More details can be seen in the comments.

**Comment by WeiTang114** [comment]
I'm closing this issue. Feel free to reopen it if there is any further problem.
