### ISSUE TITLE
depth rendering and phong shading

### ISSUE THREAD

**Issue by xuyinxuyin** [WeiTang114/BlenderPhong#3]
Hello, sorry to bother you.  it seems that the output is different from the phong shading image provided in your paper and it is similar to the depth rendering. Which settings I should modify to get the phong shading image that provided in your paper?

**Comment by WeiTang114** [comment]
Actually for the paper I used the code similar to [https://github.com/WeiTang114/3DModelViewGenerator](https://github.com/WeiTang114/3DModelViewGenerator). This repo is for other experiments.
But I think the results would be similar.
