### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by longmalongma** [WeiTang114/BlenderPhong#5]
Think you for your reply,Can you help me?How to solve this problem?
 File "/media/longma/dangjisheng_windows/1axirix/BlenderPhong-master/phong.py", line 132, in load_model
    bpy.ops.import_mesh.off(filepath=path, filter_glob='*.off')
  File "/usr/share/blender/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.import_mesh.off" error, could not be found
Error, region type 4 missing in - name:"Action", id:12

Blender quit

**Comment by DanielCWard** [comment]
It looks like you are missing the blender addon to load .off files. This is inside the submodule of the BlenderPhong repository called 'blender-off-addon'.

Is this directory empty after you cloned BlenderPhong?

If so, fetch the addon using 
`git submodule init` and `git submodule update`

With the addon present the problem should be solved and the code should run

**Comment by WeiTang114** [comment]
Thanks @DanielCWard for the reply. Closing this now.
